# Generated by Django 4.2.4 on 2023-08-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0002_alter_category_slug"),
    ]

    operations = [
        migrations.RemoveField(model_name="cart", name="price",),
        migrations.AddField(
            model_name="cart",
            name="price_db",
            field=models.DecimalField(
                db_column="price",
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=6,
            ),
            preserve_default=False,
        ),
    ]
