# Generated by Django 4.2.4 on 2023-08-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0003_remove_cart_price_cart_price_db"),
    ]

    operations = [
        migrations.RemoveField(model_name="cart", name="price_db",),
        migrations.AddField(
            model_name="cart",
            name="_price",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=6
            ),
            preserve_default=False,
        ),
    ]
