# Generated by Django 4.2.4 on 2023-08-07 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0004_remove_cart_price_db_cart__price"),
    ]

    operations = [
        migrations.RenameField(model_name="cart", old_name="_price", new_name="price",),
    ]
